### ISSUE TITLE
Discuss overall app structure

### ISSUE THREAD

**Issue by grabbou** [itemsapi/itemsapi#10]
This is actually a proposal rather than something to fix, mainly because I haven't dig into the architecture yet, but... the `server.js` is actually something we can improve in order to allow different `backends` (like elasticsearch) to be implemented in the future (the main I can think of is a graph database).

For now, we `require` the services explicitly https://github.com/itemsapi/item/blob/master/server.js#L28-L31 as well as the data and they do depend on each other (e.g. dataService requires some elastic elements - cross-folder requires), so we end up having a nice, not-that-small scope to lookup when handlers are invoked.

Imo, to improve that, we can make something like this:
```
-- backends
---- elasticsearch
-------db
-------dataService
-------index
```
and then, do:
```js
app.use(elasticSearch({connectionString}));
```

ElasticSearch can then create a connection, attach it to `request` (it's a middleware!) and attach other dataServices to request as well, so in casual request handlers you just write:

```js
router.use(elasticSearch(config));
router.get('/', function(req) {
   req.elastic.dataService(....);
});
```

All in all, you will end up with a nice layer on top of `express` that can be just dropped in to any existing app which surely will increase the possible adoption in the future :)

Another thing is the config, imo, with the middlewares pattern presented above, you can just allow user to pass config as an object to your middleware dropping the `nconf` dependency completely letting users handle the configuration on their own.

After the above are implemented, `server.js` can be moved to `examples/elastic_search/index.js` to present one of the possible ways of using the module.

**Comment by cigolpl** [comment]
From my current perspective it seems to be very smart especially that we could use:
- elasticsearch for searching, faceting and sorting
- graph database like neo4j for `items` recommendations
- redis database for counting, heavy writes and caching

I would like to see other node.js systems with such a architecture to understand all benefits and see all pros and cons.
@grabbou thanks for very valuable comment.
