### ISSUE TITLE
Search response with 400 if query contain the /, &

### ISSUE THREAD

**Issue by pilot** [itemsapi/itemsapi#126]
the problem solved if query enclosed with quotes like `"goodyear R18 245/55"`

**Comment by cigolpl** [comment]
Thank you for that! 

I will try to fix that soon with first or the second approach. Hopefully they will do the job
http://stackoverflow.com/a/31963789/659682
https://www.npmjs.com/package/string-escape

**Comment by pilot** [comment]
yes, that's it

**Comment by cigolpl** [comment]
anyway when you search by `"goodyear R18 245/55"` afaik it is searching like `"goodyear" OR "R18" OR "245/55"` but I believe it should search like `"goodyear" AND "R18" AND "245/55"`

**Comment by pilot** [comment]
you right, it should glue by AND, as usual this is make by google search

**Comment by cigolpl** [comment]
#127 should do the job here. it is merged and published

**Comment by cigolpl** [comment]
it was a good change, the search experience has improved now in all of my applications :)

**Comment by pilot** [comment]
for me too, btw we have soon publish our project build with itemsapi, would be great to add section on site with real cases

**Comment by cigolpl** [comment]
that's great news! please let me know once you finish and I could add that on itemsapi.com as a real case
