### ISSUE TITLE
Aggregation with boolean data type fields

### ISSUE THREAD

**Issue by athlonUA** [itemsapi/itemsapi#129]
i tried to append scheme with boolean data type and i wanted to add aggregation throw this field. but I didn't find any docs for this issue. Could you help me? p.s. in API i found the possibility to use `key value` fields to search items https://itemsapi.readme.io/docs/search-items , but I would like to implement the aggregation with boolean data types

**Comment by athlonUA** [comment]
I have in my head the thought that maybe aggregation is not used for Boolean data types ...

**Comment by cigolpl** [comment]
I believe you can make aggregation with boolean data type.
This is how it could look like:
![selection_403](https://cloud.githubusercontent.com/assets/1032493/16396110/6ceb6394-3cbd-11e6-9ee1-0a3a2f0f0809.jpg)

It will make for you:
![selection_404](https://cloud.githubusercontent.com/assets/1032493/16396127/7c721dd0-3cbd-11e6-9189-467ac4ef5ca5.jpg)

You could filter that by aggregation or by `key` & `val` `/api/v1/items/mycollection?key=flag&val=true` or `/api/v1/items/mycollection?key=flag&val=T`

Let me know if that is what you are looking for

**Comment by athlonUA** [comment]
YES! Thank! This is all that i need.

**Comment by cigolpl** [comment]
Cool, that's great! :)
Please keep in mind that you can use `key`, `val` or encoded `aggs={"flag":["T"]}` => `aggs=%7B%22flag%22:%5B%22F%22%5D%7D` as well. The first one is simplier but second one is more powerful

**Comment by pilot** [comment]
@cigolpl what about to add `faq` label then mark such issue with `faq` and leave it open, this is will helpful for newcomer

**Comment by athlonUA** [comment]
@cigolpl  yeah. you solved my problem as well. i prefer to use my boolean field as part of aggs query param

**Comment by cigolpl** [comment]
@pilot that's good idea! :) will try to update itemsapi.readme.io docs too!

**Comment by cigolpl** [comment]
btw: itemsapi in boolean aggregation currently operates on "T" and "F" by default and "true" / "false". this is how elasticsearch works internally https://github.com/elastic/elasticsearch/issues/2462

Not sure yet if that matters but itemsapi should be smart enough to operate on "true" / "false" by default because it could be more intuitive and simplier
