### ISSUE TITLE
Incorrect search by aggregation parameter

### ISSUE THREAD

**Issue by athlonUA** [itemsapi/itemsapi#141]
Hi! Now i tested search with different aggregation parameters and found that the search is not working correctly. 

When i sent request like this
`http://example.com/api/v1/test?aggs=%7B%22brand%22:%5B%22ac%22%5D%7D` the datas were found correctly

but when i send request like this
`http://example.com/api/v1/test?aggs=%7B%22brand%22:%5B%22AC%22%5D%7D` elastic didn't find anything

if you notice, in first request i sent `ac` and in the second one - `AC` 

I think it is not correctly and the search should be `case insensitive`

**Comment by cigolpl** [comment]
Hi Alex, I believe if you add `index`: `not_analyzed`:
```js
            "brand": {
                "type": "string",
                "store": true,
                "index": "not_analyzed"
            }
```

and remove your data and add again then it should be ok.
If that's still not working then please let me know (I've been testing here with `COMPACT` https://itemsapi.herokuapp.com/api/v1/wikipedia-cars?aggs=%7B%22class%22:%5B%22COMPACT%22%5D%7D and it was fine)

**Comment by athlonUA** [comment]
@cigolpl In my elastic scheme `index`: `not_analyzed` exists

```
            "brand": {
                "type": "string",
                "index": "not_analyzed"
            },

**Comment by cigolpl** [comment]
@athlonUA yes, you are right. My recent tests me showed me it is case sensitive though. Thanks for that. I will check it out how can we solve that easily.

**Comment by cigolpl** [comment]
@athlonUA I've made some research and it seems (at least for me) it is not easy to make `aggregation terms` case insensitive out of the box from elasticsearch. My research included mostly adding `analyser lowercase` to `brand` field. (https://gist.github.com/mtyaka/2006966)

Can you tell me more about your use case ? I had similar problem once I was building search application for movies i.e. I wanted to show all movies for specific actor like for `Robert de Niro` but with pretty URL. 
So instead that `/filter/actors/Robert de Niro` (which was simple) I wanted to make it working like `/filter/actors/robert-de-niro` and finally found solution. Let me know if your case is somehow similar then I can provide you more details

**Comment by athlonUA** [comment]
@cigolpl  In my application there are forms with input fields where the user should enter the name of brand or part of it. The users when entering brand name knows only the set of letters of brand's name word. They are don't know in which text format this names are storing in elasticseach index, e.g. `Adidas` or `aDidas` or maybe `adidas`

**Comment by athlonUA** [comment]
and what about to use the regexp expressions like this https://gist.github.com/mtyaka/2006966#file-gistfile1-sh-L38

**Comment by athlonUA** [comment]
and what do you mean about this https://gist.github.com/athlonUA/3ba6fd27df86f70cbb3bc3b13711e05a

**Comment by pilot** [comment]
@cigolpl bout case insensitive is a quite important thing to get the correct list of results.

Elastic support our of the box case insensitive search like 

https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html

http://stackoverflow.com/questions/32386355/elasticsearch-case-insensitive-term-filter-search-on-not-analyzed-field

**Comment by cigolpl** [comment]
@athlonUA thanks for your example. that's interesting and simple solution and seems should do the job (but only when "index": "analyzed"). Currently itemsapi `query` doesn't support `AND`, `OR`, wildcards, fieldnames etc like here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html (more details: #126)

We could easily add additional `querystring` besides `query` which can take values like `brand:AUDI`, `brand:aud*`, `brand:audi OR brand:bmw` etc

The problem is you would need to have  `"index": "analyzed"` for field which is not always good but https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html#case-insensitive-sorting
![selection_469](https://cloud.githubusercontent.com/assets/1032493/17004310/b3482452-4ed4-11e6-83c0-06ba29555436.jpg)

should be the solution then. I mean `brand` and `brand.raw`

That's how I see it. Let me know if that make sense

**Comment by athlonUA** [comment]
@cigolpl  

> We could easily add additional querystring besides query which can take values like brand:AUDI, brand:aud*, brand:audi OR brand:bmw etc

I think this is almost what i need. Because i want to aggregate data only by one value of brand like `brand:aud*` form your example

**Comment by cigolpl** [comment]
@athlonUA so that's cool! I've put that into new PR #142
