### ISSUE TITLE
Directly accessing elastic search data

### ISSUE THREAD

**Issue by rohit-raj** [itemsapi/itemsapi#144]
I was going through the documentation, and I find that the data is fed to the elastic search using Itemsapi and then this data is queried.
It really interested me that, how can we bring in severely huge amount of data in json file and then post it through Itemsapi. Cannot we use the elastic search directly to query ?

I wanted to implement a search application, that directly uses Itemsapi to build an API which queries the existing elastic search. This will help in reducing the task of updating the data built through itemsapi.

Any leads to this will be really helpful.

**Comment by cigolpl** [comment]
Hi @rohit-raj, how large is your json file ( in records or size) . Do you already have your data in elasticsearch or only in json ? (I will send you more info in european morning)

**Comment by rohit-raj** [comment]
Hi, I dont have any such json file as of now, but I do have data in elastic search and that is very huge, since its the production data. Hence I wanted to use the elastic data directly into the Itemsapi.
please suggest any info over this.

**Comment by cigolpl** [comment]
Yes, it would not make any sense to move it to json again.

**Comment by cigolpl** [comment]
What I would do is:

Run ItemsAPI server:
```js
var itemsapi = require('itemsapi');

itemsapi.init({
  server: {
    port: 5000
  },
  collections: {
    db: 'json',
    filename:  './collections.json'
  },
  elasticsearch: {
    host: 'localhost:9200'
  }
})

itemsapi.start(function serverStart(serverInstance) {
  var host = serverInstance.address().address;
  var port = serverInstance.address().port;
  itemsapi.get('logger').info('ItemsAPI backend started on http://%s:%s', host, port)
});
```

Create `collections.json` in root directory with your schema, aggregations and sortings (below is example). As you already have defined schema in elasticsearch I believe it can be empty here. Aggregations and sortings can be also empty

```js
[
    {
        "name": "collection_name",
        "index": "your_elastic_index_name",
        "type": "your_elastic_type_name",
        "schema": {
            "image": {
                "type": "string",
                "display": "image"
            },
            "name": {
                "type": "string",
                "store": true
            },
            "net_worth": {
                "type": "string",
                "store": true
            },
            "nationality": {
                "type": "string",
                "store": true
            }
        },
        "aggregations": {
            "nationality": {
                "type": "terms",
                "size": 15,
                "field": "nationality",
                "title": "nationality"
            }
        },
        "sortings": {
            "name": {
                "title": "name",
                "type": "normal",
                "order": "desc",
                "field": "name"
            },
            "net_worth": {
                "title": "net_worth",
                "type": "normal",
                "order": "desc",
                "field": "net_worth"
            },
            "nationality": {
                "title": "nationality",
                "type": "normal",
                "order": "desc",
                "field": "nationality"
            }
        }
    }
]
```

And once you start you can directly make request i.e. `http://localhost:5000/api/v1/items/collection_name`

**Comment by cigolpl** [comment]
I believe it could be your minimalistic / start version of `collections.json`:

```js
[
    {
        "name": "collection_name",
        "index": "your_elastic_index_name",
        "type": "your_elastic_type_name",
        "schema": {},
        "aggregations": {},
        "sortings": {}
    }
]
```

**Comment by rohit-raj** [comment]
Thank you, this is what I was looking for. One more major hurdle that I am seeing is the querying the elasticsearch with any json query, or a list of items to be searched.
I have tried using the api endpoints, like :  http://localhost:5000/api/v1/items/collection_name/:id
is there any way we could GET/POST json data to query the elastic search.

if I would like to search, for fetching all names with Rohit, with age 25 and city as Bangalore. Can this be done by posting this in Json ?
eg:
```
{
        "name" : "rohit",
        "age" : "25",
        "city" : "Bangalore"
    }
}
```

**Comment by cigolpl** [comment]
There are a few ways of querying elasticsearch through itemsapi:

http://localhost:5000/api/v1/items/collection_name?query_string=name:rohit AND age:25 AND city:Bangalore (name%3Arohit%20AND%20age%3A25%20AND%20city%3ABangalore)

http://localhost:5000/api/v1/items/collection_name?query=rohit (full text search)
http://localhost:5000/api/v1/items/collection_name?key=name&val=rohit (usually `name` in that way should have property `index`: `not_analyzed` in mapping)
http://localhost:5000/api/v1/items/collection_name/:id

Probably the first method is the most flexible but all of them have some specific purposes.

Currently fetching by json like:
```js
{
        "name" : "rohit",
        "age" : "25",
        "city" : "Bangalore"
}
``` 
is not possible but we could consider such a implementation in the future

Let me know if you have any other questions

**Comment by cigolpl** [comment]
@rohit-raj if you don't have any more question I have to close this issue.
It would be great as well if you give me some feedback what you like and what you miss in ItemsAPI or in elasticsearch just here or in the private channel because it could help me make this software better
