### ISSUE TITLE
Data searching

### ISSUE THREAD

**Issue by athlonUA** [itemsapi/itemsapi#152]
Hi @cigolpl ! I have some trouble with next:
- if i send a request like this http://example.com/api/v1/products?query=jean i receive 100 results
- if i send a request like this http://example.com/api/v1/products?query=jeans i receive 500 results

the question is about why in the first query I get fewer products than in the second query? The first request is more generalising...

**Comment by cigolpl** [comment]
Hi @athlonUA, that's good question.
What first comes to my mind is using proper analyzers to tell elasticsearch how to process and store your data internally:
- https://www.elastic.co/blog/found-text-analysis-part-1
- https://tryolabs.com/blog/2015/02/25/elasticsearch-analyzers-or-how-i-learned-to-stop-worrying-and-love-custom-filters/

Are you using it for showing standard results or for auto-complete ?

**Comment by athlonUA** [comment]
@cigolpl you mean this relates only to elasticsearch configuration? I use it for auto-complete and generally to searching

**Comment by cigolpl** [comment]
@athlonUA I believe it could be configured also in ItemsAPI configuration. I will make same tests on my local machine. 

What you want to do is `pattern` searching ? I mean for:
- `j` it shows all results which contains `j` i.e `jeans`
- `je` it shows all results which contains `je` etc

or `plural`  searching:
- for `phone` and `phones` it shows the same results ?

**Comment by athlonUA** [comment]
@cigolpl  only `pattern` searching

**Comment by cigolpl** [comment]
@athlonUA could you see if that works for you ?
-  http://example.com/api/v1/products?query_string=your_field_type:/*jean*/

(more details here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_regular_expressions)

I believe it should works but I am afraid it can be slow.

**Comment by athlonUA** [comment]
@cigolpl  as i correctly understood in the example above `your_field_type` means the concrete field like `name` or `category`? Is it hard to implement this regular expression `/*something*/` directly in api and to search the data through all the fields (like `query` value)?

**Comment by cigolpl** [comment]
Hi @athlonUA, yes it works only for one specific field :(

**Comment by cigolpl** [comment]
By the way - I consider writing additional functionality for autocomplete / suggesting in ItemsAPI using 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

I am making some research already based on nice examples and on experience with my websites http://baymard.com/blog/autocomplete-design. 

I hope you could also benefit from that in the future if I could accomplish that
