### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by athlonUA** [itemsapi/itemsapi#159]
Is it possible to implement sorting by many fields like this
```
{
    "sort" : [
        { "post_date" : "asc"},
        { "name" : "desc" },
        { "age" : "desc" }
    ],
    "query" : {...}
}

**Comment by athlonUA** [comment]
I mean something like this https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html

**Comment by cigolpl** [comment]
Hi Alex, currently only by one field but multi field searching can be also very useful.

I could make that it supports multi field sorting (asc, desc, geo) like in above doc but without `script based sorting`. Is it ok for you ?

**Comment by athlonUA** [comment]
Yes! It is be very cool 👍

**Comment by cigolpl** [comment]
Hi @athlonUA, I am setting up my todo list. What is your priority for sorting ? Would you like to have it soon in the production or it is not hurry up ?

**Comment by cigolpl** [comment]
@athlonUA it is done #163. More details in PR.
Let me know once you have any question

**Comment by athlonUA** [comment]
@cigolpl sorry for later response. I implement last update with multi-sorting but have some questions

My config of sort:

```
            "newest": {
                "title": "Newest products",
                "type": "normal",
                "sort": [
                    {
                        "date_updated_timestamp": {
                            "order": "desc"
                        }
                    },
                    {
                        "weight": {
                            "order": "desc"
                        }
                    }
                ]
            },
```

In elastic i have the new products every day but my sorting config show me the products by 11 November. Maybe i have misunderstanding in this config. For me the new products in priority. When the products sorted by date i want the products started sorting by weight? Is it possible?

**Comment by cigolpl** [comment]
Hi @athlonUA , your config looks good for me!
Please let's check if records with `date_updated_timestamp` are stored in the same way in elasticsearch. Would be also good if you make API request directly to elasticsearch because ItemsAPI `sort` works in the same way and then we will know if the issue is on the ES or ItemsAPI side

**Comment by athlonUA** [comment]
@cigolpl i think i know the cause of my problem. I check the elastic items. Due to the my config file products sorts by `date_updated_timestamp` and `weight` fields. But bigger priority has `weight` field. `Weight` field in my collection ranges from 1 to 10. And for the last 3 days products with weight 1 were updated only... But i want the products sorts by date first and then star sorts by weight. Is it possible?

**Comment by cigolpl** [comment]
@athlonUA I think it is possible to make sorting like that but it happens only if you have `date_updated_timestamp` with the same values i.e. `05-05-2015` and `05-05-2015`, then ES will take those with higher `weight` value

**Comment by athlonUA** [comment]
@cigolpl 
If i have next products:
`Date`_______`Weight`
`01-01-2016` `3`
`01-01-2016` `10`
`02-01-2016` `1`
`02-01-2016` `1`
`03-01-2016` `1`
`03-01-2016` `1`

In my case the products will be sorted:
`Date`_______`Weight`
`01-01-2016` `10`
`01-01-2016` `3`
`03-01-2016` `1`
`03-01-2016` `1`
`02-01-2016` `1`
`02-01-2016` `1`

But what can i do to receive the next sorting:
`Date`_______`Weight`
`03-01-2016` `1`
`03-01-2016` `1`
`02-01-2016` `1`
`02-01-2016` `1`
`01-01-2016` `10`
`01-01-2016` `3`

**Comment by cigolpl** [comment]
@athlonUA I see. What I can advice is run `curl -XGET localhost:4000/api/v1/collections/your_collection_name/mapping | jq '.'` to see how your fields are stored in Elasticsearch. I would also check if:

```js
            "newest": {
                "title": "Newest products",
                "type": "normal",
                "sort": [
                    {
                        "date_updated_timestamp": {
                            "order": "desc"
                        }
                    }
                ]
            }
```

works only for dates `date_updated_timestamp`. 

I.e. in one of my collection I have date type like below and sorting works good:

```js
          "created_at": {
            "format": "dateOptionalTime",
            "type": "date"
          },
```

I hope it is not the problem of multisorting.
