### ISSUE TITLE
mysql support

### ISSUE THREAD

**Issue by futureweb2020** [itemsapi/itemsapi#177]
Hello, I am using MySQL as a database.
Do you have any plan to support MySQL or can I easily modify the code to support MySQL?
Regards,

**Comment by pilot** [comment]
There is no way to replace ElasticSearch with MySQl, but it's easy to connect your mysql tables to be indexed by elasticsearch

**Comment by futureweb2020** [comment]
What I mean is to replace the underlying database MongoDB with MySQL.

**Comment by pilot** [comment]
Sure you can, mysql is not out from the box, but use it will not be big deal
