### ISSUE TITLE
AND vs OR

### ISSUE THREAD

**Issue by kevinsproles** [itemsapi/itemsapi#186]
If a user selects multiple genres, and multiple years, it should work like this:

Get movies where:

Genre is either:
**Action** or **Adventure** or **Comedy**

AND

Year is either:
**2020** or **2019** or **2018**

Currently the demo at http://localhost:3000 from the guide (https://docs.itemsapi.com/guide/movies.html) is making all these AND when they should be OR.

**Comment by cigolpl** [comment]
Hey @kevinsproles,

Thanks for pointing that out. 

If you need such a policy then you just need to set `conjunction` as `false` to `year` and `genres` fields in configuration (https://github.com/itemsapi/itemsapi/blob/master/examples/configuration-movies.json)

Hope it's gonna work for you

**Comment by kevinsproles** [comment]
ah, that's what **conjunction** means, thanks. 👍
