### ISSUE TITLE
Auto actualize documenation at the itemsapi.com from itemsapi.readme.io

### ISSUE THREAD

**Issue by pilot** [itemsapi/itemsapi#44]

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by cigolpl** [comment]
Hi @pilot, @pjedrzejewski, thanks for comment.
Probably it is not possible to get content from itemsapi.readme.io in easy way like by API.

Do you think we should keep whole documentation on itemsapi.com like it was the last time ? i.e. https://www.itemsapi.com/docs/start/overview.html (of course up-to-date)

**Comment by pilot** [comment]
not sure that copy is really required, overview is quite enough, next just use the direct links to the itemsapi.readme.io this is would be much easy at least for now
