### ISSUE TITLE
Elasticsearch 2.1 version get issue with `display` mapping param

### ISSUE THREAD

**Issue by pilot** [itemsapi/itemsapi#45]
- has unsupported parameters:  [display : image]
- has unsupported parameters:  [display : array]

in schema expample from documentaion
`"image": {"type": "string", "display": "image" },`

btw what the preffer version of elastic for current documentation state?

**Comment by cigolpl** [comment]
Thanks. This is a bug. Currently it gets data from configuration schema directly to the elasticsearch while it creates mapping which is not good.

We should create `mapper helper` which gets data from schema and translate it for valid elasticsearch schema and ignore fields like `display` which are used i.e. for dashboard:

![selection_358](https://cloud.githubusercontent.com/assets/1032493/11499645/ce0fe338-9827-11e5-9584-1f12fbde60dd.png)

As far as I remember I've tested it with elasticsearch 1.4, 1.5, 1.72 and works fine. 
Not sure about 2.1 but should be even better - I will confirm later after testing.

**Comment by cigolpl** [comment]
Couldn't reproduce that error on 2.1.
I've created #47 PR and it should solve elasticsearch mapping problem for you.

**Comment by pilot** [comment]
works perfect! :+1:
