### ISSUE TITLE
Have a plan to share http://app.itemsapi.com source code?

### ISSUE THREAD

**Issue by pilot** [itemsapi/itemsapi#48]

**Comment by pjedrzejewski** [comment]
That would be a good example how to use the library. :+1: We have our demo open source too - https://github.com/Sylius/SyliusDemo. Also makes easier to people to contribute/fix issues with demo site. :)

**Comment by cigolpl** [comment]
@pilot @pjedrzejewski, yes that's great idea. 

There is bad and good news.
1. The bad one I cannot share current template as it is not on open source license.
2. The good one we can use some open source admin bootstrap 3 template i.e. 

http://ironsummitmedia.github.io/startbootstrap-sb-admin/tables.html
Finally our dashboard will look more or less like:
![selection_363](https://cloud.githubusercontent.com/assets/1032493/11528477/4b5bb6cc-98e7-11e5-8062-1c15844490d5.png)

or https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html

![selection_367](https://cloud.githubusercontent.com/assets/1032493/11528697/a4a3ea1e-98e8-11e5-8bc7-035772730387.png)

They are not looking perfect but should be good enough for the start.
What do you think about these templates ? If they are good I can create first open source version of that.

**Comment by pjedrzejewski** [comment]
Have a look at https://almsaeedstudio.com/preview, AdminLTE is MIT license. We will use it for Sylius and look much nicer than raw Bootstrap. :)

**Comment by pjedrzejewski** [comment]
Ah sorry I have just read your note above the 2nd image. Yeah, I'd say go for AdminLTE!

**Comment by cigolpl** [comment]
@pjedrzejewski yes it looks great. Your link is a full demo and mine was probably old one, so it is even better

**Comment by pilot** [comment]
@cigolpl looks nice :+1:

**Comment by cigolpl** [comment]
The new respository with running instructions is created: https://github.com/itemsapi/dashboard.

It was great idea as the new layout is even better than that previous (paid) one and we can make it growing faster as an open source community.
http://app.itemsapi.com is updated with the new dashboard too.

**Comment by pilot** [comment]
@cigolpl respect!

**Comment by pjedrzejewski** [comment]
Woohoo! :+1:
