### ISSUE TITLE
Aggregation parse wrong the string with the spaces

### ISSUE THREAD

**Issue by pilot** [itemsapi/itemsapi#56]
Catgory name -> `kids clothes`, ultimately looks like a 

- [ ] kids (100)
- [ ] clothes (100)

**Comment by cigolpl** [comment]
you need to add `index: not_analyzed` to treat it as the whole string.

```json
"schema": {
  "category": {
    "type": "string",
    "index": "not_analyzed"
  }
}
```

Unfortunately it requires elasticsearch remapping.

**Comment by pilot** [comment]
ah, my false - sure!

**Comment by pilot** [comment]
I just use import :) this is the best things ever

**Comment by cigolpl** [comment]
Great, good to hear :)
