### ISSUE TITLE
Take configurations from environment first

### ISSUE THREAD

**Issue by cigolpl** [itemsapi/itemsapi#61]
Inspired by http://12factor.net/ and required by cloud integration i.e. with heroku.

ItemsAPI should take options from environment first and from our json configurations later i.e.:

```
NODE_ENV=production PORT=3030 ELASTICSEARCH_HOST=http://domain.url:9200 node app.js
```

Heroku example: https://blog.heroku.com/archives/2014/8/7/heroku-button

**Comment by cigolpl** [comment]
#62

**Comment by cigolpl** [comment]
It is ready!
From now we can create rest application on heroku cloud hosting for free!

Just open this url:   
https://heroku.com/deploy?template=https://github.com/itemsapi/itemsapi
and it builds itemsapi with node.js and elasticsearch


Temporarily heroku has problem with application building so wait for testing:
https://status.heroku.com/
![selection_383](https://cloud.githubusercontent.com/assets/1032493/11761997/07e20f66-a0d7-11e5-9164-247720f60aa9.png)

**Comment by pilot** [comment]
:+1:
