### ISSUE TITLE
Extract `nconf` to separate file

### ISSUE THREAD

**Issue by grabbou** [itemsapi/itemsapi#8]
Calling `nconf.get` multiple times to serialise all the elements into object may affect performance. Imo the better way would be to create something like this https://github.com/este/este/blob/master/src/server/config.js

So, ideally, this: https://github.com/itemsapi/item/blob/master/app.js#L14-L17 goes to config/index.js where the config is parsed according to current environment and then, exported with `nconf.get()`.

**Comment by cigolpl** [comment]
Thanks for comment. It is very good advice.

**Comment by cigolpl** [comment]
@grabbou thanks once again for your valuable comment. I have made a branch for it. If you find time please tell me if I can make it better
