### ISSUE TITLE
Remove winston dependency

### ISSUE THREAD

**Issue by grabbou** [itemsapi/itemsapi#9]
At least from core files, this can be easily replaced with an event emitter, or even this https://github.com/asyncly/EventEmitter2 and then, user can add in own `middlewares` by e.g. 

```js
api.on('error', ...)
api.on('elastic:query', ...)
```

**Comment by grabbou** [comment]
BTW, actually the whole `express` app is an event emitter, so we can just use it straight away w/o any extra dependencies.

**Comment by cigolpl** [comment]
Not sure if it is best solution but decided to use logger file (on top of winston). https://github.com/itemsapi/itemsapi/blob/master/config/logger.js

It is simple and very extendable - we can easily add another logging transport i.e. logstash
